### ISSUE TITLE
Settings are not displayed

### ISSUE THREAD

**Issue by Daniellop1** [lucasm/findto#1]
Hello, when I open the settings a blank window appears that has no content. I also warn you that the lower buttons do not work as they show an error message.

**Comment by lucasm** [comment]
Hi Daniel, I'm launching the new version of this project in March and this problem has already been fixed.

I realized that you forked the Findto project without attributing it to the original author, I ask you to make the credits available. Thanks =)

**Comment by Daniellop1** [comment]
Hello, sorry for the attribution I will immediately. Thanks for your reply
